#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="x86: fastcall argument analysis"
FILE=../../bins/elf/analysis/fast
CMDS='
aa
s sym.fastcaslled
afc fastcall
afva
?e
pdf~arg,local
'
EXPECT='
|   sym.fastcaslled (int arg2, int arg1, int arg_8h, int arg_ch);
|           ; var int local_20h @ ebp-0x20
|           ; var int local_1ch @ ebp-0x1c
|           ; var int local_10h @ ebp-0x10
|           ; var int local_ch @ ebp-0xc
|           ; arg int arg_8h @ ebp+0x8
|           ; arg int arg_ch @ ebp+0xc
|           ; arg int arg2 @ edx
|           ; arg int arg1 @ ecx
|           0x08048421      894de4         mov dword [local_1ch], ecx  ; arg1
|           0x08048424      8955e0         mov dword [local_20h], edx  ; arg2
|           0x08048427      8b55e4         mov edx, dword [local_1ch]
|           0x0804842a      8b45e0         mov eax, dword [local_20h]
|           0x0804842f      8945f4         mov dword [local_ch], eax
|           0x08048432      8b45e0         mov eax, dword [local_20h]
|           0x08048435      2b450c         sub eax, dword [arg_ch]
|           0x08048438      8945f0         mov dword [local_10h], eax
|           0x0804843b      ff7508         push dword [arg_8h]
|           0x0804843e      ff75f0         push dword [local_10h]
|           0x08048441      ff75f4         push dword [local_ch]
'
run_test
