#!/bin/sh
# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# "!" - run commands (via system)

NAME='dbg.dc+ds.swstep'
FILE=../../bins/arm/elf/hello_world
ARGS=-d
BROKEN=
CMDS='e scr.color=0
e scr.null=true
s entry0
s +8
db $$
dc
dc
'
EXPECT='Hello world!
'
IGNORE_ERR=0
run_test
